// <auto-generated />
using System;
using GlomilAssesment.Models.ORM.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GlomilAssesment.Migrations
{
    [DbContext(typeof(GlomilContext))]
    [Migration("20210531092740_glomil3")]
    partial class glomil3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("GlomilAssesment.Models.ORM.Entities.MathEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("UserName")
                        .HasColumnType("integer");

                    b.Property<double>("input1")
                        .HasColumnType("double precision");

                    b.Property<double>("input2")
                        .HasColumnType("double precision");

                    b.Property<double>("sonuc1")
                        .HasColumnType("double precision");

                    b.Property<double>("sonuc2")
                        .HasColumnType("double precision");

                    b.Property<double>("sonuc3")
                        .HasColumnType("double precision");

                    b.Property<double>("sonuc4")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.HasIndex("UserName");

                    b.ToTable("mathEntity");
                });

            modelBuilder.Entity("GlomilAssesment.Models.ORM.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("BornYear")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GlomilAssesment.Models.VM.MathDetailsVM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<double>("input1")
                        .HasColumnType("double precision");

                    b.Property<double>("input2")
                        .HasColumnType("double precision");

                    b.Property<double>("sonuc1")
                        .HasColumnType("double precision");

                    b.Property<double>("sonuc2")
                        .HasColumnType("double precision");

                    b.Property<double>("sonuc3")
                        .HasColumnType("double precision");

                    b.Property<double>("sonuc4")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.ToTable("mathDetails");
                });

            modelBuilder.Entity("GlomilAssesment.Models.VM.MathVM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("input1")
                        .HasColumnType("double precision");

                    b.Property<double>("input2")
                        .HasColumnType("double precision");

                    b.Property<double>("sonuc1")
                        .HasColumnType("double precision");

                    b.Property<double>("sonuc2")
                        .HasColumnType("double precision");

                    b.Property<double>("sonuc3")
                        .HasColumnType("double precision");

                    b.Property<double>("sonuc4")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.ToTable("MathVM");
                });

            modelBuilder.Entity("GlomilAssesment.Models.VM.UserRegisterVM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("BornYear")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("UserRegisterVM");
                });

            modelBuilder.Entity("GlomilAssesment.Models.ORM.Entities.MathEntity", b =>
                {
                    b.HasOne("GlomilAssesment.Models.ORM.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserName");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
